#!/bin/bash

echo "======================================"
echo "  Portfolio Admin User Setup"
echo "======================================"
echo ""
echo "Admin credentials have been configured:"
echo ""
echo "📧 Email: admin@portfolio.com"
echo "🔑 Password: Admin@123456"
echo ""
echo "======================================"
echo ""
echo "To create the admin user, please:"
echo "1. Open your browser and go to: http://localhost:5173/admin"
echo "2. Click 'Sign up' if available, or"
echo "3. Go to your Supabase Dashboard → Authentication → Users"
echo "4. Click 'Add User' and create a user with:"
echo "   - Email: admin@portfolio.com"
echo "   - Password: Admin@123456"
echo ""
echo "======================================"
echo ""
echo "Once created, you can login at:"
echo "🔗 http://localhost:5173/admin"
echo ""
